### ISSUE TITLE
Hardcoded SID ('LNX') in function backup_global_and_nameserver() of SAPHana RA

### ISSUE THREAD

**Issue by fdanapfel** [fmherschel/SAPHanaSR-old-private#37]
in version 0.152.17 the function contains the following commands which hardcode the SID to 'LNX':

    cp /hana/shared/LNX/global/hdb/custom/config/global.ini /hana/shared/LNX/global/hdb/custom/config/global.ini.$(date +"%s")
    cp /hana/shared/LNX/global/hdb/custom/config/nameserver.ini /hana/shared/LNX/global/hdb/custom/config/nameserver.ini.$(date +"%s")

'LNX' should be replaced with '$SID'

**Comment by oalbrigt** [comment]
https://github.com/fmherschel/SAPHanaSR/pull/38

**Comment by fmherschel** [comment]
Frank you are right, it should be SID instead of LNX. However it's only debugging code which is never called. Its was only to locally debug with SAP once a global.ini was damaged after a command call. We wanted to figure out which command damaged the files.
I will change the backup (debugging) function in one of the next uploads.

**Comment by fdanapfel** [comment]
Since a patch has been provided to fix this I'm closing this issue.
